import express from "express";
import bodyParser from "body-parser";
import cookieParser from "cookie-parser";
import cors from "cors";
import path from "path";
import connect from "./connect";
import {performersParse, searchPerformersParse} from "./parse";
const app = express();
const PORT = process.env.PORT || 5000;
app.use(bodyParser.urlencoded({extended: true}));
app.use(bodyParser.json());
app.use(cookieParser());
app.use(cors());
app.use(express.static("client/out"));
app.get("/api/getData/", (req: any, res: any) => connect(req, res));
app.post("/api/getPerformersData/", (req: any, res: any) => performersParse(req, res));
app.post("/api/getSearchPerformersData/", (req: any, res: any) => searchPerformersParse(req, res));
app.get("*", (req: any, res: any) => res.sendFile(path.resolve(__dirname, "client/out", "index.html")));
app.listen(PORT, () => console.log(`Server is running on ${PORT}`));
